spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      javax:
        persistence:
#          sharedCache:
#            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
#        cache:
#          use_second_level_cache: true
#          use_query_cache: true
#          region:
#            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  datasource:
    platform: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  mail:
    host: smtp.qq.com
    username: 1187697635@qq.com
    password: xzaadjblfjocgica
    properties:
      mail:
        smtp:
          auth: true
  http:
    multipart:
      enabled: true
      max-file-size: 500000KB
      max-request-size: 500000KB
  messages:
    fallback-to-system-locale: false
    basename: i18n/messages

ftp:
  address: 119.23.75.180
  port: 21
  username: ftptest
  password: ftptest
  basepath: /home/ftptest/barcode




